# Initially borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# The validity of this file can be checked here: http://lint.travis-ci.org/

language: python
sudo: false

matrix:
  include:
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: linux
      python: "3.7"
    - os: linux
      python: "3.8"

before_install:
  # Setup anaconda
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  # Create a virtual environment with the right version of python
  - conda create -n testing python=$TRAVIS_PYTHON_VERSION --yes
  - source activate testing

# Install packages
install:
  - conda install --yes cython numpy scipy h5py
  - pip install matplotlib
  - python setup.py install
  - pip install wget
  - pip install pyflakes jupyter pytest

before_script :
  # static code analysis
  #   pyflakes: mainly warnings, unused code, etc.
  - python -m pyflakes openpmd_viewer

script:
  - "python setup.py test"
