# Initially borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# The validity of this file can be checked here: http://lint.travis-ci.org/

language: python
sudo: false

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"

before_install:
  # Setup anaconda
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  # Create a virtual environment with the right version of python
  - conda create -n testing python=$TRAVIS_PYTHON_VERSION --yes
  - source activate testing

# Install packages
install:
  - conda install --yes numpy=1.15.1
  - conda install --yes cython
  - conda install --yes scipy
  - conda install --yes h5py
  - pip install matplotlib
  - python setup.py install
  - pip install wget
  - pip install pyflakes pycodestyle jupyter

before_script :
  # static code analysis
  #   pyflakes: mainly warnings, unused code, etc.
  - python -m pyflakes opmd_viewer
  #   pep8: style only, enforce PEP 8
  - python -m pycodestyle --ignore=E201,E202,E122,E127,E128,E131,W605 opmd_viewer

script:
  - "python setup.py test"
