# Initially borrowed from here:  https://gist.github.com/dan-blanchard/7045057
# The validity of this file can be checked here: http://lint.travis-ci.org/

language: python
sudo: false

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: osx
      language: cpp
      env: TRAVIS_PYTHON_VERSION=2.7

# Setup anaconda
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - conda install --yes python=$TRAVIS_PYTHON_VERSION jupyter
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pyflakes
  - python setup.py install
before_script :
  - python -m pyflakes .
script: 
  - "python setup.py test"
